### PR TITLE
Added instances to tool support

### PR DESCRIPTION
**Pull request by danielwilms**
* parse the instances in the specification
* create branches and leaves accordingly

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Still errors, or the spec is not compliant (should be fixed first), e.g.
` Error: InteriorLights.vspec: 57: Not a branch: Vehicle.Cabin.Lights.Spotlight.Row1.IsPassengerOn.`

`Error: Cabin/Cabin.vspec: 201: Not a branch: Vehicle.Cabin.SeatPosCount.`

**Comment by SebastianSchildt** [comment]
`Error: ADAS/ADAS.vspec: 86: Not a branch: Vehicle.ADAS.ObstacleDetection.DistanceToObject.`

**Comment by SebastianSchildt** [comment]
Otherwise the JSON output looks as expected. But VSS should be changed to conform to the "only branches can have instances" rule before merging this

**Comment by danielwilms** [comment]
Depends on: https://github.com/GENIVI/vehicle_signal_specification/issues/186

**Comment by danielwilms** [comment]
@gunnarx can be merged now.

**Pull request merged**
