### PR TITLE
README.md: add link to VSS Tools section of official online VSS doc

### PR DESCRIPTION
**Pull request by slawr**
The official online VSS documentation contains a section on the VSS Tools.
Follow the pattern set by the VSS README.md and link to it to aid
discoverability by newcomers.

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
I am not sure, we should link it (at this point), as I think the documentation in the main hugo docs is outdated. (And it should be discussed where tools documentation should live).

My view is: the main VSS hugo page at http://localhost:1313/vehicle_signal_specification/   should not contain any tools documentation at all, and only provide a lnik to this repo.

IN _here_ we can decide whether github Readmes are enough (I think so), or we want to set up a separate Hugo instance

**Comment by SebastianSchildt** [comment]
See also #74

**Comment by gunnarx** [comment]
Agree with Sebastian. Let's restructure the documentation of the tools.

**Comment by slawr** [comment]
Agree on the points about the different documentation levels. My thinking behind the PR was my discovery path through the doc. I found the online VSS doc early on and therefore also info on vss-tools. I have also seen links to vss-tools source in CVII. The README however limits itself to install, run and test. There is no information about what the tools are intended to do. That however can be found in the online doc including a useful diagram putting it in context with the vspec files. 

I therefore thought a simple link would help discoverability until the documentation catches up, but its a minor/trival change and not a hill I am looking to die on.

I feel I lack the deep experience of the tools to attempt rewriting the documentation. That would be best handled/discussed in an enhancement ticket I feel. So I am leaning towards simply closing this?

**Comment by danielwilms** [comment]
@gunnarx, please close as tools are not described in vss anymore.

**Comment by slawr** [comment]
Closing as requested by community

**Pull request closed without merging**
