### PR TITLE
Use of EnumMeta to refactor and improve performance

### PR DESCRIPTION
**Pull request by oliveirarleo**
Use of a new EnumMeta subclass to offer values() and an efficient from_str() in every enumeration that uses it.

### CODE REVIEW

**Review by barbieri — APPROVED** [review]
thanks!

@gunnarx, @danielwilms , @SebastianSchildt this is the first commit of my #81, it just saves the code duplication and offers an optimized reverse lookup.

**Review by SebastianSchildt — APPROVED** [review]
The Python-Fu is strong with this one. Not sure we really _need_ to bring out the metaclass gun for this problem, but in total we have

 - less lines
 - generated output similar to master branch
 
Therefore, I approve if CI run is successful

**Comment by barbieri** [comment]
well, `EnumMeta` is already a metaclass... just adding some more meat to that one :-D

**Comment by barbieri** [comment]
also, not just the 2 points, but it's also more efficient. We're replacing a linear search (on a small subset of items, but still... it's running for every node in the tree) with a constant-time lookup

**Comment by danielwilms** [comment]
@gunnarx, please start build job and merge if it runs through

**Comment by gunnarx** [comment]
Meaning and purpose was explained by @barbieri and it seems OK for me.

**Pull request merged**
