### PR TITLE
Go parser go.mod updates.

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Comment by danielwilms** [comment]
@gunnarx pls have a look

**Comment by gunnarx** [comment]
Lots of commits, merges and a conflict with master => I rebased on master and squashed everything into one commit and updated the PR.
@UlfBj Please check if 6cd6f71 contains everything we need and if it is correct.

**Comment by gunnarx** [comment]
Hmm, it does not seem quite correct to put this into only one commit.  6cd6f71 contains more than go.mod updates.  I think you had also other "bug fixes" in this PR.

**Comment by UlfBj** [comment]
Yes, it slipped into the previous PR. 
The initial parts were about go script updates, the latter about bug fixes in the parser code.
Shall I do anything to brake it up into two?

**Comment by gunnarx** [comment]
OK, I could not easily separate different parts (and not sure what is the right separation either).  So, because the changes include both go.mod updates, and several code updates, I now just renamed the squashed commit to "Updates to binary tool ".  Not ideal but the best I could do.  If the latest commit looks OK I propose we merge it.

**Comment by UlfBj** [comment]
Ok. Thanks.

**Comment by danielwilms** [comment]
@danielwilms run code and check PR

**Comment by danielwilms** [comment]
decision to merge 09/03/21

**Pull request merged**
