### PR TITLE
Fixing unit and datatypes tests

### PR DESCRIPTION
**Pull request by erikbosch**
I noticed when running "pytests test" according to the README that there were some errors due to previously changed units/types. 
This PR fixes that.

But how come that it has not been detected. Shall we consider these tests as obsolete and remove them?
Or possibly instead include them in Travis-tests so the automated tests will fail on errors?

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Never used/seen them.

Since they are there, I suggest in this PR also adding them to travis.yml, so if in the future it breaks, we can check why.

**Comment by erikbosch** [comment]
Sure, no problem, but what do we consider as the preferred way.

- Adding it directly to travis.yml, like "PYTHONPATH=. pytest"
- Or adding it to the Makefile in vehicle-signal-specification like other tools called indirectly from the Makefile, so that it will be included if you run "make all"?

**Comment by erikbosch** [comment]
Note: This PR depends on that make target "tests" have been merged, see https://github.com/GENIVI/vehicle_signal_specification/pull/249

**Comment by SebastianSchildt** [comment]
I vote merging this, once we get https://github.com/GENIVI/vehicle_signal_specification/pull/249   merged.

In the long term, build recipes/vss-tools helper scripts should move to vss-tools, but lets discuss this separately from the issue here.

This is about automatically running the tests we have, and I believe not test should go to waste :)

**Comment by gunnarx** [comment]
It failed again.  Looks like it is about the **value** metadata.  Was it recently changed to **default**?  @erikbosch can you check?

**Comment by erikbosch** [comment]
Now it worked @gunnarx . It seems that I didn't rebase my own vss-tools to latest master when I tested myself , so having a test on "value" still worked locally. But that was changed about 14 days ago by #39 so I had to remove the test on "value" here as well, so now the tests pass.

**Pull request merged**
